_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 103
            "3":
                - 13
                - 23
                - 55
            "4": 3.8.19
            "5": 0.18.0
            "8":
                - 3
                - 5
            "12": 0.18.0
            "13": windows-amd64
