_wandb:
    value:
        cli_version: 0.18.0
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_IoU
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": valid_IoU
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": valid_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 53
                - 55
                - 63
                - 74
                - 80
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.8.19
            "5": 0.18.0
            "8":
                - 3
                - 5
            "12": 0.18.0
            "13": windows-amd64
